{% set name = "qnm" %}
{% set version = "0.4.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 53332a654858633cc67d09731b8c2817b72ed48f6dabede5f583bf3a7652aee6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numba
    - numpy
    - pathlib2
    - python >={{ python_min }}
    - scipy
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - qnm

about:
  home: "https://github.com/duetosymmetry/qnm/"
  license: MIT
  license_family: MIT
  license_file: "LICENSE"
  summary: "Package for computing Kerr quasinormal mode frequencies, separation constants, and spherical-spheroidal mixing coefficients"
  description: |
    qnm is an open-source Python package for computing the Kerr
    quasinormal mode frequencies, angular separation constants,
    and spherical-spheroidal mixing coefficients. The qnm package 
    includes a Leaver solver with the Cook-Zalutskiy spectral approach
    to the angular sector, and a caching mechanism to avoid repeating
    calculations.
  doc_url: "https://qnm.readthedocs.io/"
  dev_url: "https://github.com/duetosymmetry/qnm/"

extra:
  recipe-maintainers:
    - duetosymmetry
